version: '3.8'

services:
  metro:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker_compose
    working_dir: /app
    depends_on:
      - zero
      - alpha

  zero:
    image: dgraph/dgraph:latest
    volumes:
      - /usr/local/var/run/dgraph:/dgraph
    ports:
      - "5080:5080"
      - "6080:6080"
    restart: on-failure
    command: dgraph zero --my=zero:5080

  alpha:
    image: dgraph/dgraph:latest
    volumes:
      - /usr/local/var/run/dgraph:/dgraph
    ports:
      - "8080:8080"
      - "9080:9080"
    restart: on-failure
    command: dgraph alpha --lru_mb 2048 --zero=zero:5080 --whitelist 0.0.0.0/0

  ratel:
    image: dgraph/dgraph:latest
    ports:
      - "8000:8000"
    command: dgraph-ratel
